### ISSUE TITLE
halfdim is a boolean value

### ISSUE THREAD

**Issue by kris-anderson** [tiiiecherle/osx_install_config#1]
https://github.com/tiiiecherle/osx_install_config/blob/17a8b1ccb24745afaafec56daaba71315f1cfaad/11_system_and_app_preferences/11c_macos_preferences_mojave.sh#L1226

`man pmset`

> halfdim - display sleep will use an intermediate half-brightness state between full brightness and fully off  (value = 0/1)

**Comment by tiiiecherle** [comment]
Thanks for the hint, fixed in [https://github.com/tiiiecherle/osx_install_config/commit/a200230cec34131f2b5c98249a2c048b72de6145](https://github.com/tiiiecherle/osx_install_config/commit/a200230cec34131f2b5c98249a2c048b72de6145) ;)
