### ISSUE TITLE
Use `mas` to install applications from the App Store

### ISSUE THREAD

**Issue by espoelstra** [tiiiecherle/osx_install_config#2]
Install it using `brew install mas` then run `mas list` to see what applications the current Apple ID has available. The downside is the newer versions of macOS broke the method that it used to log into the App Store programmatically, so you might need to do something tricky like unlocking the login keychain, then populating the App Store entry manually for `mas` to find. I haven't reset a Mac in a while to test this, but I plan on doing so soon.

There are some tools that do something similar like the `xcode-install` gem and its `xcversion install` command that can take your Apple ID as arguments or environment variables and perform an install of Xcode via the App Store. If you don't unlock the login keychain first you will get an error about saving the credentials to the keychain during the `xcversion install`, this also means that other commands like `mas` if run afterwards won't be able to use the credentials.

**Comment by tiiiecherle** [comment]
Hey, thanks for your message. But unfortunately I do not see the "issue".

I already implemented installing App Store apps with `mas` in this script
[https://github.com/tiiiecherle/osx_install_config/blob/master/05_homebrew_and_casks/5b_homebrew_cask/6_mas_appstore.sh](https://github.com/tiiiecherle/osx_install_config/blob/master/05_homebrew_and_casks/5b_homebrew_cask/6_mas_appstore.sh).

It also works around the issue with the appstore login by asking the password upfront and does the login via applescript.

If you are using homebrew, casks and mas you can also use [https://github.com/tiiiecherle/osx_install_config/blob/master/05_homebrew_and_casks/5b_homebrew_cask/0_run_all.command](https://github.com/tiiiecherle/osx_install_config/blob/master/05_homebrew_and_casks/5b_homebrew_cask/0_run_all.command) and put all apps and commands you would like to install in the respective lists in [https://github.com/tiiiecherle/osx_install_config/tree/master/05_homebrew_and_casks/5b_homebrew_cask/_lists](https://github.com/tiiiecherle/osx_install_config/tree/master/05_homebrew_and_casks/5b_homebrew_cask/_lists). I use it that way for years.

Please let me know if this was the answer to your question. Thank, have a great day.

Perhaps I have to take some time to update the readme to reflect all that ;)

**Comment by tiiiecherle** [comment]
Can this be considered solved?

**Comment by espoelstra** [comment]
Yes, I totally missed the fact that you'd fixed this in your code and you'd actually shared your ingenious workaround in the `mas` repo already.
