### ISSUE TITLE
Screen saver "Start after" comma doesn't work?

### ISSUE THREAD

**Issue by gandalfsaxe** [tiiiecherle/osx_install_config#3]
If I run `defaults -currentHost write com.apple.ScreenSaver idleTime -int 0`, wit this or any other number than 0, it doesn't change the setting? It just stays at 20 min:

<img width="780" alt="image" src="https://user-images.githubusercontent.com/12127864/62429544-35b62500-b710-11e9-8f29-edcca3350531.png">

**Comment by tiiiecherle** [comment]
Hey, thanks for the feedback. I just tried with 10.14 and 10.15 and both seem to work fine after a reboot.

Could you please try setting the value, then check if it was set correctly and then reboot?
```
defaults -currentHost write com.apple.ScreenSaver idleTime -int 0
defaults -currentHost read com.apple.ScreenSaver
reboot
```
Some settings need services to be restarted. I just checked successfully that this works for me without reboot:
```
defaults -currentHost write com.apple.ScreenSaver idleTime -int 120
defaults -currentHost read com.apple.ScreenSaver
for app in "cfprefsd" "System Preferences"; do
     killall "${app}" > /dev/null 2>&1
done
```

Would be nice to have a short feedback if this issue can be closed.

**Comment by gandalfsaxe** [comment]
I'll check later tonight or tomorrow at the latest and get back to you

**Comment by gandalfsaxe** [comment]
Hey sorry about the extra time, life happened :)
I've been testing this a bunch just now, and I don't really understand it's behavior.

If I first run:
`defaults -currentHost write com.apple.ScreenSaver idleTime -int 0`
or any other supported number, by which I mean 0, 1, 2, 5, 10, 20, 30, 60 minutes (any other number will set it to default 20 min). Then running:
`defaults -currentHost read com.apple.ScreenSaver`
It confirms that `idleTime` has been set.

However after that, restarting does not apply the change, only running this does:
```
for app in "cfprefsd" "System Preferences"; do
     killall "${app}" > /dev/null 2>&1
done
```

In fact, restarting just resets the setting to `idleTime = 1200`, no matter what I set it to. Thus only running the set of commands above applies the change, and as mentioned restarting even resets them. Is this expected behavior? Shouldn't just restarting also apply the change?

So yes thanks, it works! Just trying to work out why restarting doesn't seem to work, but works against.

**Comment by tiiiecherle** [comment]
Hey, I don't know if this is the expected behavior. I also think it should work after setting and rebooting. But when figuring out other settings I noticed sometimes services have to be restarted to make it work, too.
I´m glad that you got it working with the additional commands/workaround.

**Comment by gandalfsaxe** [comment]
Alright. Thanks for the help, and I'll be sure to look around this repo more for inspiration 👍

**Comment by gandalfsaxe** [comment]
Just a quick follow up question if you don'y mind.

I'm now trying to disable these four shortcuts in Mission Control:
![image](https://user-images.githubusercontent.com/12127864/63474441-784e6000-c479-11e9-921f-4554f49761a3.png)

I found the relevant lines for one of them in your script [here](https://github.com/tiiiecherle/osx_install_config/blob/f513c52fab832439dafa07445463982eb4286bf6/11_system_and_app_preferences/11c_macos_preferences_10_15.sh#L479):

```
disable application windows
/usr/libexec/PlistBuddy ~/Library/Preferences/com.apple.symbolichotkeys.plist -c 'Delete AppleSymbolicHotKeys:33'
/usr/libexec/PlistBuddy ~/Library/Preferences/com.apple.symbolichotkeys.plist -c 'Add AppleSymbolicHotKeys:33:enabled bool false'
```

Once again, it doesn't actually work / apply. The setting is still set in System Preferences -> Mission Control, and the shortcut still works. I tried these two things:

`killall Dock`

and

```
for app in "cfprefsd" "System Preferences"; do
     killall "${app}" > /dev/null 2>&1
done
```

I've found other people for whom this approach clearly [worked recently](https://apple.stackexchange.com/questions/344494/how-to-disable-default-mission-control-shortcuts-in-terminal) (unclear if it was on Mojave though). Any suggestions?

**Comment by tiiiecherle** [comment]
disabling application windows is working for me with the exact commands above after a logout in 10.14.6 Did not try 10.15 though. Can you confirm that? If not try

```
/usr/libexec/PlistBuddy ~/Library/Preferences/com.apple.symbolichotkeys.plist -c 'Delete AppleSymbolicHotKeys:33'
/usr/libexec/PlistBuddy ~/Library/Preferences/com.apple.symbolichotkeys.plist -c 'Add AppleSymbolicHotKeys:33:enabled bool false'
defaults read ~/Library/Preferences/com.apple.symbolichotkeys.plist
```

and then logout and back in.

**Comment by gandalfsaxe** [comment]
I'm on 10.14.6 as well. Ah yes, it works if I log out and in again.

Do you know if any way to force update System Preferences to reflect the change that doens't involve logging out / restarting?

Alternatively, I could also just run everything and restart at the end. That seems to be your approach, so I guess I could also just abandon my attempts to make everything refresh, and end my script with a system restart too.

**Comment by tiiiecherle** [comment]
I'm sorry, for this situation I don`t know a way to make this work without logout or restart. As more and more options seem to need this the safest way is to logout or reboot after setting all the options.
