### ISSUE TITLE
Any solution for "Require Password [X time] after sleep or screen saver begins"?

### ISSUE THREAD

**Issue by gandalfsaxe** [tiiiecherle/osx_install_config#4]
On line [1078](https://github.com/tiiiecherle/osx_install_config/blob/f513c52fab832439dafa07445463982eb4286bf6/11_system_and_app_preferences/11c_macos_preferences_10_15.sh#L1078) of `11c_macos_preferences_10_15.sh`:

```
### no longer working
    # 0 = no, 1 = yes
    #defaults -currentHost write com.apple.screensaver askForPassword -int 0
```

Is there any fix for this aside from applying this manually?

**Comment by gandalfsaxe** [comment]
Looks like it's not possible via plist changes anymore: https://stackoverflow.com/questions/45867402/macos-10-13-high-sierra-no-longer-stores-screensaver-settings-in-com-apple-scr

Instead it can only be done by applying a profile If I understand correctly. You may close this.

**Comment by tiiiecherle** [comment]
No, I don't know another solution. As I don`t use/need this setting I have not tried the profile workflow. Thanks for the link. I will add it to the script as a reference.
