### ISSUE TITLE
Update Homebrew Cask URL

### ISSUE THREAD

**Issue by reitermarkus** [tiiiecherle/osx_install_config#5]
Hi, we just wanted to let you know that you are still linking to the old Homebrew Cask homepage (`caskroom.io`) in [`README.md`](https://github.com/tiiiecherle/osx_install_config/blob/da45b48212c5fff6b5e875823beb0c51c75ece96/README.md). This domain expired a few years ago and is not controlled by Homebrew anymore.

When you get a chance, please update the link to https://brew.sh/ or https://formulae.brew.sh/cask/.

Thank you,
the Homebrew team.

**Comment by tiiiecherle** [comment]
Hey, thanks for the hint. I will push a lot of changes to the repo today or in the next days when batch-scripts are done in their first version. This will make the install/restore even easier and faster by running multiple scripts in a row. When pushing the changes I will include yours. I already changed them in the local readme file.

As this gives me the chance to say thank you to the amazing work you all do with the homebrew and homebrew-cask projects ;) I really like them and use them a lot. Really great work.

One question though. I know that there is a lot of discussion going on about it or at least has been in the past. I still think there should be a better and nicer looking way of updating formulae and casks. That`s why I created my own solution here:
[https://github.com/tiiiecherle/osx_install_config/tree/master/03_homebrew_casks_and_mas/3c_homebrew_formulae_and_casks_update](https://github.com/tiiiecherle/osx_install_config/tree/master/03_homebrew_casks_and_mas/3c_homebrew_formulae_and_casks_update)

I´m sure the code could be improved but it`s working well. Is there any chance to include this somehow or port something like this to ruby to make it part of the official project?

In addition I especially like the cleaning, java cleaning and special actions after install (e.g. LibreOffice Language Pack).

Have a nice sunday. Kind regards.

**Comment by reitermarkus** [comment]
Thanks for the kind words!

> Is there any chance to include this somehow or port something like this to ruby to make it part of the official project?

I'd suggest submitting a feature request with a concrete explanation of what you would expect the upgrade process to look like. Other than that I can't really say whether or not something like this could be included.

**Comment by tiiiecherle** [comment]
O.k., thanks. I just pushed the changes.
