### ISSUE TITLE
AppStore.app disabled, how to sign-in?

### ISSUE THREAD

**Issue by YannBrrd** [tiiiecherle/osx_install_config#6]
Hi,

How can I signin in App Store while it is disabled? osascripts fail, and API disabled... so `mas` fails... :(

**Comment by tiiiecherle** [comment]
Hey,

thanks for your messge, I think you already got your answer here ;)

[https://github.com/mas-cli/mas/issues/164#issuecomment-546954555](https://github.com/mas-cli/mas/issues/164#issuecomment-546954555)

Sorry, I don`t know another way.
