### ISSUE TITLE
MacOS 13 version check error messages show "this script is only compatible with macos 12, exiting..."

### ISSUE THREAD

**Issue by sdossick** [tiiiecherle/osx_install_config#7]
This is a very minor issue that obviously doesn't affect actual functionality, would you like a PR for it?  PS Thanks for the great work unearthing how to set all of these from the command line!

**Comment by tiiiecherle** [comment]
You're welcome. I'm glad if it helps other users.
Thanks for letting me know about the typos.
I pushed the fixes with a few other changes a minute ago ;)
