### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by tnxz** [tiiiecherle/osx_install_config#8]
you might want to look at [mackup](https://github.com/lra/mackup) for backing up configs for homebrew casks.

**Comment by tiiiecherle** [comment]
Hey @tnxz,

thanks for the url to mackup. The tool looks really good.

For my backups and restore I use a highly customizable [file](https://github.com/tiiiecherle/osx_install_config/blob/master/07_backup_and_restore_script/list/backup_restore_list.txt) which has entries for every file and folder I like to backup and restore.

This includes E-Mails, personal files and application settings. I only added entries for files and folders that I need to backup and restore. You can always customize this file to backup/restore everything you need.

Mackup supports a lot of apps and can help me adding entries to my file for new entries in my file in the future.

**Comment by tiiiecherle** [comment]
I added a url to mackup in in the first lines of my config file. Thanks again for the url.

**Comment by tnxz** [comment]
is the config idempotent ?

**Comment by tiiiecherle** [comment]
Sorry, I don't know what you mean by "idempotent" in this context.
For each entry in my config file the script checks if the respective file/folder exists on your mac. If it does exist, it will be backed up, if not, the entry will be ignored.

**Comment by tnxz** [comment]
like rerunning doesnt affect the system, it seems it is.
