### ISSUE TITLE
skhd accessibility permission

### ISSUE THREAD

**Issue by tnxz** [tiiiecherle/osx_install_config#9]
so how could i make skhd have accessibility permissions as writing to tcc.db isn't working

**Comment by tiiiecherle** [comment]
Hey, to access tcc.db you need to change the SIP (System Integrity Protection) parameters as stated in the Readme in 
[1 NVRAM, system integrity protection and secure boot](https://github.com/tiiiecherle/osx_install_config#1nvram-system-integrity-protection-and-secure-boot).

All scripts are only tested with these permissions
`csrutil enable --without debug --without fs`

**Comment by tnxz** [comment]
thanks for that
